# Generated by Django 6.0.6 on 2026-06-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('title_he', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_he', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('video', 'Video file'), ('audio', 'Audio file'), ('youtube', 'YouTube link'), ('other', 'Other link')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='sermons/')),
                ('url', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='sermons/thumbnails/')),
                ('date', models.DateField()),
                ('speaker', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
