# Generated by Django 6.0.6 on 2026-06-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='sermon',
            name='content_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='content_he',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='content_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='media_type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video file'), ('audio', 'Audio file'), ('youtube', 'YouTube link'), ('other', 'Other link')], default='text', max_length=10),
        ),
    ]
