# Generated by Django 6.0.6 on 2026-06-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_album_photo_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField()),
                ('text_ru', models.TextField(blank=True)),
                ('text_he', models.TextField(blank=True)),
                ('reference_en', models.CharField(max_length=100)),
                ('reference_ru', models.CharField(blank=True, max_length=100)),
                ('reference_he', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
