# Generated by Django 6.0.6 on 2026-06-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dailyverse'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=300)),
                ('question_ru', models.CharField(blank=True, max_length=300)),
                ('question_he', models.CharField(blank=True, max_length=300)),
                ('answer_en', models.TextField()),
                ('answer_ru', models.TextField(blank=True)),
                ('answer_he', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
