# Generated by Django 6.0.6 on 2026-07-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_leadershipphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='Canonical format for tel: links, e.g. +972552998715', max_length=32)),
                ('phone_display', models.CharField(help_text='Display format, e.g. 055-299-8715', max_length=32)),
                ('whatsapp_number', models.CharField(help_text='Digits only for wa.me links, e.g. 972552998715', max_length=32)),
                ('address_en', models.CharField(blank=True, max_length=255)),
                ('address_ru', models.CharField(blank=True, max_length=255)),
                ('address_he', models.CharField(blank=True, max_length=255)),
                ('address_es', models.CharField(blank=True, max_length=255)),
                ('service_hours_en', models.CharField(blank=True, max_length=255)),
                ('service_hours_ru', models.CharField(blank=True, max_length=255)),
                ('service_hours_he', models.CharField(blank=True, max_length=255)),
                ('service_hours_es', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
